start backend without using nodemon
Fixes:
```
> nodemon server.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '../lib/cli'
Require stack:
- /var/app/current/node_modules/.bin/nodemon
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/var/app/current/node_modules/.bin/nodemon:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/app/current/node_modules/.bin/nodemon' ]
}
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>